[package]
name = "lsp_rust_test"
version = "0.1.0"
authors = ["Alessandro Piras <laynor@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bar = {version = "0.1.0", path = "./bar"}
byteorder = "1.3.4"
